// <auto-generated />
using DynamicDashboardSample.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicDashboardSample.Migrations
{
    [DbContext(typeof(DynamicDasboardDbContext))]
    partial class DynamicDasboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("DynamicDashboardSample.Domain.Models.Stage", b =>
                {
                    b.Property<int>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("StageId");

                    b.ToTable("Stage");
                });

            modelBuilder.Entity("DynamicDashboardSample.Domain.Models.Vysor", b =>
                {
                    b.Property<int>("VysorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("VysorId");

                    b.ToTable("Vysor");
                });

            modelBuilder.Entity("DynamicDashboardSample.Domain.Models.VysorStage", b =>
                {
                    b.Property<int>("VysorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<int>("PosX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PosY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeH")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeW")
                        .HasColumnType("INTEGER");

                    b.HasKey("VysorId", "StageId");

                    b.HasIndex("StageId");

                    b.ToTable("VysorStage");
                });

            modelBuilder.Entity("DynamicDashboardSample.Domain.Models.VysorStage", b =>
                {
                    b.HasOne("DynamicDashboardSample.Domain.Models.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DynamicDashboardSample.Domain.Models.Vysor", "Vysor")
                        .WithMany()
                        .HasForeignKey("VysorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");

                    b.Navigation("Vysor");
                });
#pragma warning restore 612, 618
        }
    }
}
